name: Compile FFmpeg
on: [push]

defaults: 
  run: 
    shell: "cmd"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: enter Developer Command Prompt and enter msys2
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\vcvars64.bat"
          where cl
          where link
          where lib
          set MSYS2_PATH_TYPE=inherit
          C:\msys64\usr\bin\bash.exe -lc "which cl"
          ##add cl to first of path
          #cldir=$(dirname $(which cl))
          #echo $cldir
          #export PATH=cldir:$PATH
          #echo $PATH
          where cl
          where link
          where lib
