name: Compile FFmpeg
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: list files
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
        #run: dir "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build"