name: Compile FFmpeg
on: [push]

defaults: 
  run: 
    shell: "msys2"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
      - name: list files(check vcvars64.bat exists)
        shell: "cmd"
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
        #run: dir "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build"
      - name: enter Developer Command Prompt and enter msys2
        shell: "msys2"
        run: |
          "/C/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          which cl
          which link
          which lib
          ##add cl to first of path
          #cldir=$(dirname $(which cl))
          #echo $cldir
          #export PATH=cldir:$PATH
          #echo $PATH
          where cl
          where link
          where lib
